package com.example.accessingdatamysql;

import java.time.LocalDate;
import java.util.Optional;
import java.util.stream.IntStream;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class MainController {
	@Autowired // This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private UserRepository userRepository;

	@PostMapping(path="/add") // Map ONLY POST Requests
	public @ResponseBody String addNewUser (@RequestParam String name
			, @RequestParam String email) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request

		IntStream.range(1,10).parallel().forEach(i ->{

			try {
				System.out.println("DATA :: "+i+":: Date ::"+LocalDate.now().toString());
				Optional<User> n1 = userRepository.findByDate(LocalDate.now().toString());
				//Optional<User> n1 = userRepository.findById(i);

				User n = n1.get();
				//User n = new User();
				n.setName("MAMA "+i);
				n.setEmail("gmail.com");
				n.setDate(LocalDate.now().plusDays(1).toString());
				userRepository.save(n);
			}catch(Exception e) {
				System.out.println("ERROR :: "+e.getMessage());
			}
		});
		return "Saved";
	}

	@GetMapping(path="/all")
	public @ResponseBody Iterable<User> getAllUsers() {
		// This returns a JSON or XML with the users
		return userRepository.findAll();
	}
}
